"use client";

import { Printer } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo } from "react";

import { Button } from "@/components/Button";
import { Container } from "@/components/Container";
import { Heading } from "@/components/Heading";
import { Text } from "@/components/Text";
import { mockAIProvider } from "@/features/buildpath/engine";
import { useBuildPathAnswers } from "@/features/buildpath/useBuildPathAnswers";
import { useBuildPathStore } from "@/providers/BuildPathStoreProvider";

/**
 * CLAUDE.md Milestone 14 §27's PDF export — a dedicated print-optimized
 * view plus the browser's native print-to-PDF, rather than a PDF
 * generation library. Honest scope: this produces a real, working PDF via
 * "Save as PDF" in the print dialog, without adding a rendering
 * dependency to the project for one export path. `print:hidden` keeps the
 * chrome (nav, print button) out of the saved document.
 */
export default function BuildPathPrintPage() {
  const answers = useBuildPathAnswers();
  const projectTypes = useBuildPathStore((state) => state.projectTypes);
  const summary = useMemo(() => mockAIProvider.generateSummary(answers), [answers]);

  useEffect(() => {
    const timer = window.setTimeout(() => window.print(), 300);
    return () => window.clearTimeout(timer);
  }, []);

  return (
    <Container size="content" className="space-y-8 py-12">
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <Button asChild variant="outline" size="sm">
          <Link href="/buildpath">Back to BuildPath</Link>
        </Button>
        <Button size="sm" iconLeft={Printer} onClick={() => window.print()}>
          Print / Save as PDF
        </Button>
      </div>

      <div className="space-y-6">
        <div className="space-y-1">
          <Heading variant="h2" as="h1">
            Your BuildPath Plan
          </Heading>
          {projectTypes.length > 0 && <Text variant="caption">{projectTypes.join(", ")}</Text>}
        </div>

        <div>
          <Heading variant="h5" as="h2">
            Vision
          </Heading>
          <Text variant="body">{summary.vision}</Text>
        </div>

        <div>
          <Heading variant="h5" as="h2">
            Problem
          </Heading>
          <Text variant="body">{summary.problem}</Text>
        </div>

        {summary.mvpFeatureNames.length > 0 && (
          <div>
            <Heading variant="h5" as="h2">
              MVP features
            </Heading>
            <ul className="list-inside list-disc space-y-0.5">
              {summary.mvpFeatureNames.map((name) => (
                <li key={name}>
                  <Text variant="body" as="span">
                    {name}
                  </Text>
                </li>
              ))}
            </ul>
          </div>
        )}

        <div>
          <Heading variant="h5" as="h2">
            Next steps
          </Heading>
          <ul className="list-inside list-disc space-y-0.5">
            {summary.nextSteps.map((step) => (
              <li key={step}>
                <Text variant="body" as="span">
                  {step}
                </Text>
              </li>
            ))}
          </ul>
        </div>

        <Text variant="caption" className="text-muted pt-4">
          Generated by Byld IQ BuildPath.
        </Text>
      </div>
    </Container>
  );
}
